# Generated by Django 3.2 on 2022-02-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='discussionc',
        ),
    ]
