# Generated by Django 3.2 on 2022-02-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_rename_post_comment_discussionc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='discussionc',
            new_name='discussion',
        ),
    ]
