# Generated by Django 3.2 on 2022-02-28 22:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_rename_discussionc_comment_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, verbose_name=django.contrib.auth.models.User),
        ),
    ]
