# Generated by Django 3.2 on 2022-02-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='slug',
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
