# Generated by Django 3.2 on 2022-03-02 14:58

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0007_auto_20220228_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, verbose_name=django.contrib.auth.models.User),
        ),
    ]
