# Generated by Django 3.2 on 2022-03-02 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0008_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='downVote',
            field=models.ManyToManyField(blank=True, related_name='discussion_downvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
