# Generated by Django 3.2 on 2022-03-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_discussion_downvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='downVote',
            new_name='down_vote',
        ),
    ]
