# Generated by Django 3.2 on 2022-03-03 09:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0010_rename_downvote_discussion_down_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
