# Generated by Django 3.2 on 2022-03-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0011_categorys_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='discussion',
            new_name='Discussion',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='categorys',
            new_name='category',
        ),
    ]
